name: Run Security Scan on Test Branch

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Security Scan
        run: echo "Running scan on test branch..."
